spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_app?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
logging:
  level:
    com.hew.springcloudserver.mapper: debug