spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_app?useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
#    以下mvc和resources均是扔出404错误
  mvc:
    throw-exception-if-no-handler-found: true
  #    Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  thymeleaf:
    cache: false
  resources:
#    whether to enable default resource handling
    add-mappings: false
#logging:
#  level:
#    com.hew.springcloudserver.mapper: debug
mybatis-plus:
  type-enums-package: com.hew.springcloudserver.enums