server:
  port: 8081
spring:
  application:
    name: spring-cloud-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: *